### ISSUE TITLE
Doesn't support Node v8.9.3

### ISSUE THREAD

**Issue by amitkhare** [shershen08/vuejs-sound-player#14]
**$ Error:** vue-audio@0.0.10: The engine "node" is incompatible with this module. Expected version "8.0.0".

**Comment by shershen08** [comment]
I see @amitkhare 
Do you propose smth like `"node": "^8.0.0"`

**Comment by shershen08** [comment]
added, will release today

**Comment by amitkhare** [comment]
Thank you. :+1:
