### ISSUE TITLE
Stop all instances when pressing play

### ISSUE THREAD

**Issue by blyleven** [shershen08/vuejs-sound-player#15]
Hi! 

First of all, thanks for this great repo! 

At the moment i'm using this in a project where there can be a lot of instances on a single page. I'd like to pause (stop) all other players when pressing play on another player, so only 1 audio file would be playing at a time.

I know I have to do something within the pause() function, but don't exactly know where to start. Anybody here who wants to help?

**Comment by blyleven** [comment]
For anybody looking for a solution, this helped me out. If there are better solutions, let me know :)

`
pause: function () {
      
      $.each($('audio'), function () {
        this.pause(); // Stop playing
        this.currentTime = 0; // Reset time
      });

      this.paused = !this.paused;
      (this.paused) ? this.audio.pause() : this.audio.play()
},
`

**Comment by lanzhiheng** [comment]
I think it is better to use and global variable to store the vue instance which is playing, If you want to play anthor one you can stop the current one which stop in global variable.

In addition if you want to use jquery to select all the audio I suggest you to extra it to a single function, and it can call by another method. You can use vue's [event bus](https://alligator.io/vuejs/global-event-bus/ ) to register an global event, and emit it in this method.

**Comment by shershen08** [comment]
@blyleven thanks for brining it in!

I think that iterating over all `<vue-audio>` tags in a specific container could be a handy solution for the problem you have.

**Comment by shershen08** [comment]
So I'll close this for now since it has no actual bug in the plugin.
I suppose that could be helpful for others so feel free to provide and update in the README as , say usage examples section
