### ISSUE TITLE
Fix sass Issue and variables which not be initilized.

### ISSUE THREAD

**Issue by lanzhiheng** [shershen08/vuejs-sound-player#3]
1. sass issue
![image](https://user-images.githubusercontent.com/8858472/33113133-c070ce1a-cf91-11e7-8b66-84c76d4f883c.png)

2. variable issue
![image](https://user-images.githubusercontent.com/8858472/33113153-db8adeac-cf91-11e7-9f84-94bba3668f27.png)

**Comment by shershen08** [comment]
Merged your PR with some minor changes
Thanks for the input!
Also published the updated `vue-audio@0.0.8`

**Comment by lanzhiheng** [comment]
@shershen08 Thanks, I create an issue #5 for modifying the stylesheet. I want to remove the bootstrap dependency.
