### ISSUE TITLE
Write some test for this components

### ISSUE THREAD

**Issue by lanzhiheng** [shershen08/vuejs-sound-player#9]

**Comment by lanzhiheng** [comment]
I think we need some test for the component's behavior.

**Comment by shershen08** [comment]
considering the size of the plugin code I would not see the test coverage as absolute must.
of course feel free to add and create PR!

**Comment by shershen08** [comment]
@lanzhiheng  thanks for all the latest proposals and improvements!

**Comment by lanzhiheng** [comment]
@shershen08 Thanks, I think If you have time you can merge the PR https://github.com/shershen08/vuejs-sound-player/pull/7 and release the new version of this plugins, and then we can continue to do better for it.
